---
- from: '2020-01-13 12:00:00 UTC'
  stable_version: '15.1'
  legacy_version: '15.0'
  testing_version: '15.2'
  testing_state: 'Alpha'
- from: '2019-05-22 12:00:00 UTC'
  stable_version: '15.1'
  legacy_version: '15.0'
- from: '2019-04-16 12:00:00 UTC'
  stable_version: '15.0'
  legacy_version: '42.3'
  testing_version: '15.1'
  testing_state: 'RC'
- from: '2019-02-13 12:00:00 UTC'
  stable_version: '15.0'
  legacy_version: '42.3'
  testing_version: '15.1'
  testing_state: 'Beta'
- from: '2018-09-30 12:00:00 UTC'
  stable_version: '15.0'
  legacy_version: '42.3'
  testing_version: '15.1'
  testing_state: 'Alpha'
- from: '2018-05-25 12:00:00 UTC'
  stable_version: '15.0'
  legacy_version: '42.3'
- from: '2018-01-31 00:00:00'
  stable_version: '42.3'
  testing_version: '15.0'
  testing_state: 'Beta'
  legacy_version: '42.2'
- from: '2017-07-26 00:00:00'
  stable_version: '42.3'
  legacy_version: '42.2'
- from: '2017-07-08 00:00:00'
  stable_version: '42.2'
  testing_version: '42.3'
  testing_state: 'RC'
  legacy_version: '42.1'
- from: '2016-11-16 00:00:00'
  stable_version: '42.2'
  legacy_version: '42.1'
